services:
  db:
    image: mariadb:12
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    env_file: ".env"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
